# daroach.net
#
# VueJS Nuxt Web Server
#
# Author: Gagan Daroach gagandaroach@gmail.com
version: "3"

networks:
  default:
    external: true
    name: daroachnetwork

services:
  webserver:
    build: ./www
    restart: unless-stopped
    ports:
      - 20000:3000
    environment:
      - VIRTUAL_HOST=hsulympics.com
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=hsulympics.com
      - LETSENCRYPT_EMAIL=gagandaroach@gmail.com
    command: "npm run start"
